apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web-deployment
  namespace: todons
spec:
  selector:
    matchLabels:
      app: todo-web
  template:
    metadata:
      labels:
        app: todo-web
    spec:
      containers:
        - name: todo-web
          image: todo-web:v1
          imagePullPolicy: Never
          env:
            - name: API_URL
              value: http://localhost:30005
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          ports:
            - containerPort: 80
